// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mocozmswkciamznderss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vY296bXN3a2NpYW16bmRlcnNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2Njg0ODksImV4cCI6MjA3MDI0NDQ4OX0.oUuC-NWygaagRY13BcOTdfftEt9SeCPBT0Wc_Vyot8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});